apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::851725625129:user/dew    # Update as needed with your IAM user ARN
      username: dew    # Update as needed with your desired Kubernetes username
      groups:
        - system:masters    # Gives admin access to cluster
