apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: dev-nest-eks-secret-provider-class # Update as needed, must match Deployment volumeAttributes.secretProviderClass
  namespace: dev-nest-eks-namespace # Update as needed, must match Deployment and Service metadata.namespace
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:us-east-2:851725625129:secret:dev-app-secrets-uc8krw"    # Update as needed, must match your Secrets Manager secret ARN
        objectAlias: "dev-nest-eks-secrets"    # Update as needed
